# Define the services (containers) we want to run
services:

  # 1. The PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: visitor-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # 2. The Spring Boot Application Service
  app:
    build: .
    container_name: visitor-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

# Define the volume to persist database data
volumes:
  postgres-data: