# Define the services (containers) we want to run
services:
  # 2. The Spring Boot Application Service
  app:
    build: .
    container_name: visitor-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.yinjxabfetclaulckpyu.supabase.co:5432/postgres

# Define the volume to persist database data
volumes:
  postgres-data: